import java.util.List;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Random;

public class HigherLowerGame {

    /**
     * Determines if the user's guess is correct.
     * 
     * @param userInput   The user's guess ('h' for higher, 'l' for lower).
     * @param currentNumber The current number shown to the user.
     * @param nextNumber    The next number generated by the game.
     * @return true if the user's guess is correct, false otherwise.
     */
    public boolean guessHigherOrLower(char userInput, int currentNumber, int nextNumber) {
        return (userInput == 'h') ? nextNumber > currentNumber : nextNumber < currentNumber;
    }

    /**
     * Creates a duplicate of the list.
     * 
     * @param original The original list to duplicate.
     * @param deepCopy If true, creates a new list with the same values; otherwise, creates a shallow copy (effective only for non-primitive types).
     * @return A new list containing the copied values.
     */
    public static List<Integer> duplicateList(List<Integer> original, boolean deepCopy) {
        if (deepCopy) {
            return new ArrayList<>(original);
        } else {
            // For Integer, shallow copy still involves creating a new list with the same Integer objects
            return original;
        }
    }


    /**
     * Print numbers and their states safely using an Iterator.
     * 
     * @param numbers The list of numbers to process.
     */
    public void printNumbersAndStates(List<Integer> numbers) {
        Iterator<Integer> iterator = numbers.iterator();
        while (iterator.hasNext()) {
            Integer number = iterator.next();
            // Implement logic for printing number and its state here
            // Example: System.out.println("Number: " + number);
            iterator.remove();
        }
    }

    /**
     * Initiates and runs a simple console-based Higher or Lower game.
     */
    public void playGame() {
        Random random = new Random();
        Scanner scanner = new Scanner(System.in);
        int score = 0;
        int currentNumber = random.nextInt(100) + 1; // Random number between 1 and 100

        System.out.println("Welcome to the Higher or Lower Game!");

        while (true) {
            System.out.println("Current number: " + currentNumber);
            System.out.print("Will the next number be higher (h) or lower (l)? Type 'q' to quit: ");
            char userInput = scanner.next().charAt(0);

            if (userInput == 'q') {
                break;
            }

            int nextNumber = random.nextInt(100) + 1; // Generate next number

            if (guessHigherOrLower(userInput, currentNumber, nextNumber)) {
                System.out.println("Correct! The next number was " + nextNumber);
                score++;
            } else {
                System.out.println("Wrong! The next number was " + nextNumber);
                score--; // Or just keep it the same or some other logic based on desired rules
            }

            currentNumber = nextNumber;
            System.out.println("Current score: " + score);
        }

        scanner.close();
        System.out.println("Thank you for playing! Your final score was: " + score);
    }

    public static void main(String[] args) {
        HigherLowerGame game = new HigherLowerGame();
        game.playGame();
    }
}